// @generated by protobuf-ts 2.9.1 with parameter generate_dependencies,optimize_code_size
// @generated from protobuf file "etherean.proto" (package "etherean", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { EthereanGrpc } from "./etherean";
import type { UniswapRewardsWidgetReply } from "./etherean";
import type { UniswapRewardsRequest } from "./etherean";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { LidoRewardsWidgetReply } from "./etherean";
import type { LidoRewardsRequest } from "./etherean";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service etherean.EthereanGrpc
 */
export interface IEthereanGrpcClient {
    /**
     * @generated from protobuf rpc: GetLidoRewardsWidget(etherean.LidoRewardsRequest) returns (etherean.LidoRewardsWidgetReply);
     */
    getLidoRewardsWidget(input: LidoRewardsRequest, options?: RpcOptions): UnaryCall<LidoRewardsRequest, LidoRewardsWidgetReply>;
    /**
     * @generated from protobuf rpc: GetUniswapRewardsWidget(etherean.UniswapRewardsRequest) returns (etherean.UniswapRewardsWidgetReply);
     */
    getUniswapRewardsWidget(input: UniswapRewardsRequest, options?: RpcOptions): UnaryCall<UniswapRewardsRequest, UniswapRewardsWidgetReply>;
}
/**
 * @generated from protobuf service etherean.EthereanGrpc
 */
export class EthereanGrpcClient implements IEthereanGrpcClient, ServiceInfo {
    typeName = EthereanGrpc.typeName;
    methods = EthereanGrpc.methods;
    options = EthereanGrpc.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetLidoRewardsWidget(etherean.LidoRewardsRequest) returns (etherean.LidoRewardsWidgetReply);
     */
    getLidoRewardsWidget(input: LidoRewardsRequest, options?: RpcOptions): UnaryCall<LidoRewardsRequest, LidoRewardsWidgetReply> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<LidoRewardsRequest, LidoRewardsWidgetReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetUniswapRewardsWidget(etherean.UniswapRewardsRequest) returns (etherean.UniswapRewardsWidgetReply);
     */
    getUniswapRewardsWidget(input: UniswapRewardsRequest, options?: RpcOptions): UnaryCall<UniswapRewardsRequest, UniswapRewardsWidgetReply> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<UniswapRewardsRequest, UniswapRewardsWidgetReply>("unary", this._transport, method, opt, input);
    }
}
