// @generated by protobuf-ts 2.9.1 with parameter generate_dependencies,optimize_code_size
// @generated from protobuf file "uniswap.proto" (package "etherean.uniswap", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
import { Money } from "./money";
import { Decimal } from "./decimal";
/**
 * @generated from protobuf message etherean.uniswap.Token
 */
export interface Token {
    /**
     * @generated from protobuf field: string name = 1;
     */
    name: string;
    /**
     * @generated from protobuf field: string symbol = 2;
     */
    symbol: string;
    /**
     * @generated from protobuf field: uint32 decimals = 3;
     */
    decimals: number;
}
/**
 * @generated from protobuf message etherean.uniswap.TokenFilter
 */
export interface TokenFilter {
    /**
     * @generated from protobuf field: string name = 1;
     */
    name: string;
}
/**
 * @generated from protobuf message etherean.uniswap.TokenInfo
 */
export interface TokenInfo {
    /**
     * @generated from protobuf field: etherean.uniswap.Token token = 1;
     */
    token?: Token;
    /**
     * @generated from protobuf field: google.type.Decimal deposited_amount = 2;
     */
    depositedAmount?: Decimal;
    /**
     * @generated from protobuf field: google.type.Decimal collected_fees = 3;
     */
    collectedFees?: Decimal;
    /**
     * @generated from protobuf field: google.type.Decimal withdrawn_fees = 4;
     */
    withdrawnFees?: Decimal;
    /**
     * @generated from protobuf field: google.type.Money deposited_amount_fiat = 5;
     */
    depositedAmountFiat?: Money;
    /**
     * @generated from protobuf field: google.type.Money collected_fees_fiat = 6;
     */
    collectedFeesFiat?: Money;
    /**
     * @generated from protobuf field: google.type.Money withdrawn_fees_fiat = 7;
     */
    withdrawnFeesFiat?: Money;
}
// @generated message type with reflection information, may provide speed optimized methods
class Token$Type extends MessageType<Token> {
    constructor() {
        super("etherean.uniswap.Token", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "symbol", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "decimals", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message etherean.uniswap.Token
 */
export const Token = new Token$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TokenFilter$Type extends MessageType<TokenFilter> {
    constructor() {
        super("etherean.uniswap.TokenFilter", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message etherean.uniswap.TokenFilter
 */
export const TokenFilter = new TokenFilter$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TokenInfo$Type extends MessageType<TokenInfo> {
    constructor() {
        super("etherean.uniswap.TokenInfo", [
            { no: 1, name: "token", kind: "message", T: () => Token },
            { no: 2, name: "deposited_amount", kind: "message", T: () => Decimal },
            { no: 3, name: "collected_fees", kind: "message", T: () => Decimal },
            { no: 4, name: "withdrawn_fees", kind: "message", T: () => Decimal },
            { no: 5, name: "deposited_amount_fiat", kind: "message", T: () => Money },
            { no: 6, name: "collected_fees_fiat", kind: "message", T: () => Money },
            { no: 7, name: "withdrawn_fees_fiat", kind: "message", T: () => Money }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message etherean.uniswap.TokenInfo
 */
export const TokenInfo = new TokenInfo$Type();
