FROM mcr.microsoft.com/devcontainers/typescript-node:1-18

RUN curl -sSL "https://github.com/fullstorydev/grpcurl/releases/download/v1.8.8/grpcurl_1.8.8_linux_x86_64.tar.gz" | tar -xz -C /usr/local/bin
