// @generated by protobuf-ts 2.9.1 with parameter generate_dependencies,optimize_code_size
// @generated from protobuf file "amount.proto" (package "etherean.type", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
import { Decimal } from "./decimal";
/**
 * @generated from protobuf message etherean.type.Money
 */
export interface Money {
    /**
     * @generated from protobuf field: string currency = 1;
     */
    currency: string;
    /**
     * @generated from protobuf field: google.type.Decimal value = 2;
     */
    value?: Decimal;
}
/**
 * @generated from protobuf message etherean.type.Amount
 */
export interface Amount {
    /**
     * @generated from protobuf field: google.type.Decimal ui_amount = 1;
     */
    uiAmount?: Decimal;
    /**
     * @generated from protobuf field: etherean.type.Money fiat_amount = 2;
     */
    fiatAmount?: Money;
}
// @generated message type with reflection information, may provide speed optimized methods
class Money$Type extends MessageType<Money> {
    constructor() {
        super("etherean.type.Money", [
            { no: 1, name: "currency", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "value", kind: "message", T: () => Decimal }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message etherean.type.Money
 */
export const Money = new Money$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Amount$Type extends MessageType<Amount> {
    constructor() {
        super("etherean.type.Amount", [
            { no: 1, name: "ui_amount", kind: "message", T: () => Decimal },
            { no: 2, name: "fiat_amount", kind: "message", T: () => Money }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message etherean.type.Amount
 */
export const Amount = new Amount$Type();
