// @generated by protobuf-ts 2.9.1 with parameter generate_dependencies,optimize_code_size
// @generated from protobuf file "chain_id.proto" (package "etherean.type", syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum etherean.type.ChainID
 */
export enum ChainID {
    /**
     * @generated from protobuf enum value: CHAIN_ID_UNSPECIFIED = 0;
     */
    CHAIN_ID_UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: CHAIN_ID_ETHEREUM = 1;
     */
    CHAIN_ID_ETHEREUM = 1,
    /**
     * @generated from protobuf enum value: CHAIN_ID_GOERLI = 5;
     */
    CHAIN_ID_GOERLI = 5,
    /**
     * @generated from protobuf enum value: CHAIN_ID_SEPOLIA = 11155111;
     */
    CHAIN_ID_SEPOLIA = 11155111
}
