// @generated by protobuf-ts 2.9.1 with parameter generate_dependencies,optimize_code_size
// @generated from protobuf file "curve.proto" (package "etherean.type", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
import { Decimal } from "./decimal";
import { Money } from "./amount";
/**
 * @generated from protobuf message etherean.type.CurveBalance
 */
export interface CurveBalance {
    /**
     * @generated from protobuf field: string token = 1;
     */
    token: string;
    /**
     * @generated from protobuf field: etherean.type.Money amount = 2;
     */
    amount?: Money;
    /**
     * @generated from protobuf field: etherean.type.Money fiat = 3;
     */
    fiat?: Money;
    /**
     * @generated from protobuf field: google.type.Decimal percentage = 4;
     */
    percentage?: Decimal;
}
// @generated message type with reflection information, may provide speed optimized methods
class CurveBalance$Type extends MessageType<CurveBalance> {
    constructor() {
        super("etherean.type.CurveBalance", [
            { no: 1, name: "token", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "amount", kind: "message", T: () => Money },
            { no: 3, name: "fiat", kind: "message", T: () => Money },
            { no: 4, name: "percentage", kind: "message", T: () => Decimal }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message etherean.type.CurveBalance
 */
export const CurveBalance = new CurveBalance$Type();
