// @generated by protobuf-ts 2.9.1 with parameter generate_dependencies,optimize_code_size
// @generated from protobuf file "history.proto" (package "etherean.history", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { HistoryService } from "./history";
import type { HistoryEntryResponse } from "./history";
import type { HistoryEntryRequest } from "./history";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { HistoryResponse } from "./history";
import type { HistoryRequest } from "./history";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service etherean.history.HistoryService
 */
export interface IHistoryServiceClient {
    /**
     * @generated from protobuf rpc: GetWalletHistory(etherean.history.HistoryRequest) returns (etherean.history.HistoryResponse);
     */
    getWalletHistory(input: HistoryRequest, options?: RpcOptions): UnaryCall<HistoryRequest, HistoryResponse>;
    /**
     * @generated from protobuf rpc: GetWalletHistoryEntry(etherean.history.HistoryEntryRequest) returns (etherean.history.HistoryEntryResponse);
     */
    getWalletHistoryEntry(input: HistoryEntryRequest, options?: RpcOptions): UnaryCall<HistoryEntryRequest, HistoryEntryResponse>;
}
/**
 * @generated from protobuf service etherean.history.HistoryService
 */
export class HistoryServiceClient implements IHistoryServiceClient, ServiceInfo {
    typeName = HistoryService.typeName;
    methods = HistoryService.methods;
    options = HistoryService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetWalletHistory(etherean.history.HistoryRequest) returns (etherean.history.HistoryResponse);
     */
    getWalletHistory(input: HistoryRequest, options?: RpcOptions): UnaryCall<HistoryRequest, HistoryResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<HistoryRequest, HistoryResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetWalletHistoryEntry(etherean.history.HistoryEntryRequest) returns (etherean.history.HistoryEntryResponse);
     */
    getWalletHistoryEntry(input: HistoryEntryRequest, options?: RpcOptions): UnaryCall<HistoryEntryRequest, HistoryEntryResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<HistoryEntryRequest, HistoryEntryResponse>("unary", this._transport, method, opt, input);
    }
}
