// @generated by protobuf-ts 2.9.1 with parameter generate_dependencies,optimize_code_size
// @generated from protobuf file "summer_fi.proto" (package "etherean.summerfi", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
import { Token } from "./assets";
import { Decimal } from "./decimal";
import { Money } from "./amount";
/**
 * @generated from protobuf message etherean.summerfi.Liquidation
 */
export interface Liquidation {
    /**
     * @generated from protobuf field: etherean.type.Money price = 1;
     */
    price?: Money;
    /**
     * @generated from protobuf field: google.type.Decimal price_bellow = 2;
     */
    priceBellow?: Decimal;
}
/**
 * @generated from protobuf message etherean.summerfi.Collateral
 */
export interface Collateral {
    /**
     * @generated from protobuf field: google.type.Decimal locked = 1;
     */
    locked?: Decimal;
    /**
     * @generated from protobuf field: etherean.type.Money locked_fiat = 2;
     */
    lockedFiat?: Money;
    /**
     * @generated from protobuf field: etherean.assets.Token token_meta = 3;
     */
    tokenMeta?: Token;
}
/**
 * @generated from protobuf message etherean.summerfi.Collateralization
 */
export interface Collateralization {
    /**
     * @generated from protobuf field: google.type.Decimal ratio = 1;
     */
    ratio?: Decimal;
    /**
     * @generated from protobuf field: google.type.Decimal ratio_on_next_price = 2;
     */
    ratioOnNextPrice?: Decimal;
}
/**
 * @generated from protobuf message etherean.summerfi.Vault
 */
export interface Vault {
    /**
     * @generated from protobuf field: google.type.Decimal token_amount = 1;
     */
    tokenAmount?: Decimal;
    /**
     * @generated from protobuf field: etherean.assets.Token token_meta = 2;
     */
    tokenMeta?: Token;
}
/**
 * @generated from protobuf message etherean.summerfi.Available
 */
export interface Available {
    /**
     * @generated from protobuf field: google.type.Decimal withdraw = 1;
     */
    withdraw?: Decimal;
    /**
     * @generated from protobuf field: google.type.Decimal generate = 2;
     */
    generate?: Decimal;
}
// @generated message type with reflection information, may provide speed optimized methods
class Liquidation$Type extends MessageType<Liquidation> {
    constructor() {
        super("etherean.summerfi.Liquidation", [
            { no: 1, name: "price", kind: "message", T: () => Money },
            { no: 2, name: "price_bellow", kind: "message", T: () => Decimal }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message etherean.summerfi.Liquidation
 */
export const Liquidation = new Liquidation$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Collateral$Type extends MessageType<Collateral> {
    constructor() {
        super("etherean.summerfi.Collateral", [
            { no: 1, name: "locked", kind: "message", T: () => Decimal },
            { no: 2, name: "locked_fiat", kind: "message", T: () => Money },
            { no: 3, name: "token_meta", kind: "message", T: () => Token }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message etherean.summerfi.Collateral
 */
export const Collateral = new Collateral$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Collateralization$Type extends MessageType<Collateralization> {
    constructor() {
        super("etherean.summerfi.Collateralization", [
            { no: 1, name: "ratio", kind: "message", T: () => Decimal },
            { no: 2, name: "ratio_on_next_price", kind: "message", T: () => Decimal }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message etherean.summerfi.Collateralization
 */
export const Collateralization = new Collateralization$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Vault$Type extends MessageType<Vault> {
    constructor() {
        super("etherean.summerfi.Vault", [
            { no: 1, name: "token_amount", kind: "message", T: () => Decimal },
            { no: 2, name: "token_meta", kind: "message", T: () => Token }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message etherean.summerfi.Vault
 */
export const Vault = new Vault$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Available$Type extends MessageType<Available> {
    constructor() {
        super("etherean.summerfi.Available", [
            { no: 1, name: "withdraw", kind: "message", T: () => Decimal },
            { no: 2, name: "generate", kind: "message", T: () => Decimal }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message etherean.summerfi.Available
 */
export const Available = new Available$Type();
