// @generated by protobuf-ts 2.9.1 with parameter generate_dependencies,optimize_code_size
// @generated from protobuf file "u256.proto" (package "etherean.type", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message etherean.type.DecU256
 */
export interface DecU256 {
    /**
     * @generated from protobuf field: string value = 1;
     */
    value: string; // dec repr of u256
}
// @generated message type with reflection information, may provide speed optimized methods
class DecU256$Type extends MessageType<DecU256> {
    constructor() {
        super("etherean.type.DecU256", [
            { no: 1, name: "value", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message etherean.type.DecU256
 */
export const DecU256 = new DecU256$Type();
